name: Deploy

on:
    push:
        branches:
            - "master"

jobs:
    build-storybook:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"

            - name: Install Packages
              run: yarn install --immutable

            - name: Build Storybook
              run: yarn build-storybook

            - uses: actions/upload-artifact@v3
              with:
                  name: built-storybook
                  path: ./storybook-static
                  if-no-files-found: error
                  retention-days: 1

    build-app:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Branch
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "yarn"

            - name: Install Packages
              run: yarn install --immutable

            - name: Nextjs Build Cache
              uses: actions/cache@v3
              with:
                  path: |
                      ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx', '**.json') }}
                  restore-keys: |
                      ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

            - name: Build Next App
              run: |
                  yarn build
                  yarn export

            - run: touch out/.nojekyll

            - uses: actions/upload-artifact@v3
              with:
                  name: built-app
                  path: ./out
                  if-no-files-found: error
                  retention-days: 1

    deploy:
        runs-on: ubuntu-latest
        needs: [build-storybook, build-app]
        steps:
            - name: Download Built App
              uses: actions/download-artifact@v3
              with:
                  name: built-app
                  path: out

            - name: Download Built Storybook
              uses: actions/download-artifact@v3
              with:
                  name: built-storybook
                  path: out/storybook

            - name: Deploy
              uses: s0/git-publish-subdir-action@master
              env:
                  REPO: self
                  BRANCH: gh-pages
                  FOLDER: out
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
